"""Consts used by SENEC.Home."""

from homeassistant.const import POWER_WATT, ENERGY_KILO_WATT_HOUR, UNIT_PERCENTAGE

DOMAIN = "senec_home"
DATA_UPDATED = f"{DOMAIN}_data_updated"

# Key: ['json_key', 'name', unit, icon]
SENSOR_TYPES = {
    "stat_state": ["ENERGY.STAT_STATE", "State", None, "",],
    "power_consumption": [
        "ENERGY.GUI_HOUSE_POW",
        "Power Consumption",
        POWER_WATT,
        "mdi:flash",
    ],
    "solar_power": [
        "ENERGY.GUI_INVERTER_POWER",
        "Solar Power",
        POWER_WATT,
        "mdi:solar-power",
    ],
    "grid_import": [
        "ENERGY.GUI_GRID_POW",
        "Grid Power Import",
        POWER_WATT,
        "mdi:transmission-tower",
    ],
    "grid_export": [
        "ENERGY.GUI_GRID_POW",
        "Grid Power Export",
        POWER_WATT,
        "mdi:transmission-tower",
    ],
    "battery_charge": [
        "ENERGY.GUI_BAT_DATA_POWER",
        "Battery Charge",
        POWER_WATT,
        "mdi:battery-plus",
    ],
    "battery_discharge": [
        "ENERGY.GUI_BAT_DATA_POWER",
        "Battery Discharge",
        POWER_WATT,
        "mdi:battery-minus",
    ],
    "battery_level": [
        "ENERGY.GUI_BAT_DATA_FUEL_CHARGE",
        "Accu Level",
        UNIT_PERCENTAGE,
        "mdi:battery",
    ],
    "solar_power_total": [
        "STATISTIC.LIVE_PV_GEN",
        "Solar Power Total",
        ENERGY_KILO_WATT_HOUR,
        "mdi:solar-power",
    ],
    "grid_import_total": [
        "STATISTIC.LIVE_GRID_IMPORT",
        "Net Import Total",
        ENERGY_KILO_WATT_HOUR,
        "mdi:transmission-tower",
    ],
    "grid_export_total": [
        "STATISTIC.LIVE_GRID_EXPORT",
        "Net Export Total",
        ENERGY_KILO_WATT_HOUR,
        "mdi:transmission-tower",
    ],
    "bat_charged_total": [
        "STATISTIC.LIVE_BAT_CHARGE",
        "Accu Charged Total",
        ENERGY_KILO_WATT_HOUR,
        "mdi:battery-plus",
    ],
    "bat_discharged_total": [
        "STATISTIC.LIVE_BAT_DISCHARGE",
        "Accu Discharged Total",
        ENERGY_KILO_WATT_HOUR,
        "mdi:battery-minus",
    ],
    "consumption_total": [
        "STATISTIC.LIVE_HOUSE_CONS",
        "House Power Total",
        ENERGY_KILO_WATT_HOUR,
        "mdi:flash",
    ],
}

SENEC_STATE = {
    0: "INITIALZUSTAND",
    1: "KEINE KOMMUNIKATION LADEGERAET",
    2: "FEHLER LEISTUNGSMESSGERAET",
    3: "RUNDSTEUEREMPFAENGER",
    4: "ERSTLADUNG",
    5: "WARTUNGSLADUNG",
    6: "WARTUNGSLADUNG FERTIG",
    7: "WARTUNG NOTWENDIG",
    8: "MAN. SICHERHEITSLADUNG",
    9: "SICHERHEITSLADUNG FERTIG",
    10: "VOLLLADUNG",
    11: "AUSGLEICHSLADUNG: LADEN",
    12: "SULFATLADUNG: LADEN",
    13: "AKKU VOLL",
    14: "LADEN",
    15: "AKKU LEER",
    16: "ENTLADEN",
    17: "PV + ENTLADEN",
    18: "NETZ + ENTLADEN",
    19: "PASSIV",
    20: "AUSGESCHALTET",
    21: "EIGENVERBRAUCH",
    22: "NEUSTART",
    23: "MAN. AUSGLEICHSLADUNG: LADEN",
    24: "MAN. SULFATLADUNG: LADEN",
    25: "SICHERHEITSLADUNG",
    26: "AKKU-SCHUTZBETRIEB",
    27: "EG FEHLER",
    28: "EG LADEN",
    29: "EG ENTLADEN",
    30: "EG PASSIV",
    31: "EG LADEN VERBOTEN",
    32: "EG ENTLADEN VERBOTEN",
    33: "NOTLADUNG",
    34: "SOFTWAREAKTUALISIERUNG",
    35: "FEHLER: NA-SCHUTZ",
    36: "FEHLER: NA-SCHUTZ NETZ",
    37: "FEHLER: NA-SCHUTZ HARDWARE",
    38: "KEINE SERVERVERBINDUNG",
    39: "BMS FEHLER",
    40: "WARTUNG: FILTER",
    41: "SCHLAFMODUS",
    42: "WARTE AUF ÜBERSCHUSS",
    43: "KAPAZITÄTSTEST: LADEN",
    44: "KAPAZITÄTSTEST: ENTLADEN",
    45: "MAN. SULFATLADUNG: WARTEN",
    46: "MAN. SULFATLADUNG: FERTIG",
    47: "MAN. SULFATLADUNG: FEHLER",
    48: "AUSGLEICHSLADUNG: WARTEN",
    49: "NOTLADUNG: FEHLER",
    50: "MAN: AUSGLEICHSLADUNG: WARTEN",
    51: "MAN: AUSGLEICHSLADUNG: FEHLER",
    52: "MAN: AUSGLEICHSLADUNG: FERTIG",
    53: "AUTO: SULFATLADUNG: WARTEN",
    54: "LADESCHLUSSPHASE",
    55: "BATTERIETRENNSCHALTER AUS",
    56: "PEAK-SHAVING: WARTEN",
    57: "FEHLER LADEGERAET",
    58: "NPU-FEHLER",
    59: "BMS OFFLINE",
    60: "WARTUNGSLADUNG FEHLER",
    61: "MAN. SICHERHEITSLADUNG FEHLER",
    62: "SICHERHEITSLADUNG FEHLER",
    63: "KEINE MASTERVERBINDUNG",
    64: "LITHIUM SICHERHEITSMODUS AKTIV",
    65: "LITHIUM SICHERHEITSMODUS BEENDET",
    66: "FEHLER BATTERIESPANNUNG",
    67: "BMS DC AUSGESCHALTET",
    68: "NETZINITIALISIERUNG",
    69: "NETZSTABILISIERUNG",
    70: "FERNABSCHALTUNG",
    71: "OFFPEAK-LADEN",
    72: "FEHLER HALBBRÜCKE",
    73: "BMS: FEHLER BETRIEBSTEMPERATUR",
    74: "FACOTRY SETTINGS NICHT GEFUNDEN",
    75: "NETZERSATZBETRIEB",
    76: "NETZERSATZBETRIEB AKKU LEER",
    77: "NETZERSATZBETRIEB FEHLER",
    78: "INITIALISIERUNG",
    79: "INSTALLATIONSMODUS",
    80: "NETZAUSFALL",
    81: "BMS UPDATE ERFORDERLICH",
    82: "BMS KONFIGURATION ERFORDERLICH",
    83: "ISOLATIONSTEST",
    84: "SELBSTTEST",
    85: "EXTERNE STEUERUNG",
    86: "TEMPERATUR SENSOR FEHLER",
    87: "NETZBETREIBER: LADEN GESPERRT",
    88: "NETZBETREIBER: ENTLADEN GESPERRT",
    89: "RESERVEKAPAZITÄT",
    90: "SELBSTTEST FEHLER",
    91: "ISOLATIONSFEHLER",
}
